# fly.toml app configuration file generated for exampleallstream on 2025-06-04T18:12:35Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'exampleallstream'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 2048
